"""Extra beginner lessons for WordFluent's starter language courses."""

from copy import deepcopy


def _vocabulary(*items):
    return [
        {
            "term": term,
            "pronunciation": pronunciation,
            "meaning": meaning,
            "example": example,
            "example_meaning": example_meaning,
        }
        for term, pronunciation, meaning, example, example_meaning in items
    ]


def _choice(prompt, answer, explanation, options):
    return {
        "type": "multiple_choice",
        "prompt": prompt,
        "answer": answer,
        "explanation": explanation,
        "options": options,
        "words": [],
        "accepted_answers": [],
    }


def _order(prompt, answer, explanation, words, accepted_answers=None):
    return {
        "type": "word_order",
        "prompt": prompt,
        "answer": answer,
        "explanation": explanation,
        "options": [],
        "words": words,
        "accepted_answers": accepted_answers or [],
    }


def _lesson(
    lesson_id,
    title,
    icon,
    objective,
    vocabulary,
    grammar_title,
    grammar_summary,
    order_prompt,
    order_answer,
    order_explanation,
    order_words,
    accepted_answers=None,
):
    terms = [item[0] for item in vocabulary]
    first = vocabulary[0]
    second = vocabulary[1]

    return {
        "id": lesson_id,
        "title": title,
        "icon": icon,
        "objective": objective,
        "estimated_minutes": 6,
        "xp_reward": 25,
        "coin_reward": 10,
        "vocabulary": _vocabulary(*vocabulary),
        "grammar": {
            "title": grammar_title,
            "summary": grammar_summary,
        },
        "exercises": [
            _choice(
                f"Which expression means ‘{first[2]}’?",
                first[0],
                f"{first[0]} means ‘{first[2]}’.",
                [terms[2], terms[0], terms[4], terms[3]],
            ),
            _choice(
                f"Which expression means ‘{second[2]}’?",
                second[0],
                f"{second[0]} means ‘{second[2]}’.",
                [terms[3], terms[1], terms[0], terms[4]],
            ),
            _order(
                order_prompt,
                order_answer,
                order_explanation,
                order_words,
                accepted_answers,
            ),
        ],
    }


FRENCH_EXTRA_LESSONS = [
    _lesson(
        "fr-beg-4",
        "Family and People",
        "👨‍👩‍👧",
        "Talk about close family members.",
        [
            (
                "La famille",
                "lah fah-MEE-yuh",
                "Family",
                "Voici ma famille.",
                "This is my family.",
            ),
            (
                "La mère",
                "lah mehr",
                "Mother",
                "Ma mère s'appelle Léa.",
                "My mother's name is Léa.",
            ),
            (
                "Le père",
                "luh pehr",
                "Father",
                "Mon père travaille ici.",
                "My father works here.",
            ),
            (
                "Le frère",
                "luh frehr",
                "Brother",
                "J'ai un frère.",
                "I have a brother.",
            ),
            (
                "La sœur",
                "lah suhr",
                "Sister",
                "C'est ma sœur.",
                "She is my sister.",
            ),
        ],
        "Mon and ma",
        (
            "Use mon before a masculine family word and ma before a "
            "feminine family word: mon père, ma mère."
        ),
        "Arrange: She is my sister.",
        "C'est ma sœur",
        "Use ma because sœur is feminine.",
        ["sœur", "C'est", "ma"],
        ["Cest ma soeur"],
    ),
    _lesson(
        "fr-beg-5",
        "Numbers and Age",
        "🔢",
        "Count a few things and say your age.",
        [
            ("Un", "uhn", "One", "J'ai un livre.", "I have one book."),
            ("Deux", "duh", "Two", "J'ai deux amis.", "I have two friends."),
            ("Dix", "dees", "Ten", "Il est dix heures.", "It is ten o'clock."),
            (
                "Quatorze",
                "kah-TORZ",
                "Fourteen",
                "J'ai quatorze ans.",
                "I am fourteen years old.",
            ),
            (
                "Quel âge as-tu ?",
                "kel ahzh ah-TEW",
                "How old are you? — informal",
                "Quel âge as-tu ?",
                "How old are you?",
            ),
        ],
        "Talking about age",
        (
            "French uses avoir, meaning ‘to have’, for age. Say j'ai, "
            "then the number, then ans."
        ),
        "Arrange: I am fourteen years old.",
        "J'ai quatorze ans",
        "Age follows the pattern j'ai + number + ans.",
        ["ans", "quatorze", "J'ai"],
        ["Jai quatorze ans"],
    ),
    _lesson(
        "fr-beg-6",
        "Food and Ordering",
        "🥖",
        "Name simple foods and order politely.",
        [
            (
                "Le pain",
                "luh pan",
                "Bread",
                "Je mange du pain.",
                "I eat bread.",
            ),
            (
                "Le fromage",
                "luh froh-MAHZH",
                "Cheese",
                "J'aime le fromage.",
                "I like cheese.",
            ),
            (
                "L'eau",
                "loh",
                "Water",
                "Je bois de l'eau.",
                "I drink water.",
            ),
            (
                "Je voudrais…",
                "zhuh voo-DREH",
                "I would like…",
                "Je voudrais du pain.",
                "I would like some bread.",
            ),
            (
                "L'addition",
                "lah-dee-SYOHN",
                "The bill or check",
                "L'addition, s'il vous plaît.",
                "The bill, please.",
            ),
        ],
        "Ordering with je voudrais",
        (
            "Use je voudrais for a polite order. Use du, de la, or de "
            "l' before food and drink."
        ),
        "Arrange: I would like some water.",
        "Je voudrais de l'eau",
        "Use de l' before a noun beginning with a vowel.",
        ["l'eau", "Je", "de", "voudrais"],
        ["Je voudrais de leau"],
    ),
    _lesson(
        "fr-beg-7",
        "School and Daily Life",
        "🎒",
        "Describe simple parts of your daily routine.",
        [
            (
                "L'école",
                "lay-KOHL",
                "School",
                "Je vais à l'école.",
                "I go to school.",
            ),
            (
                "Étudier",
                "ay-tew-dee-YAY",
                "To study",
                "J'étudie le français.",
                "I study French.",
            ),
            (
                "Travailler",
                "trah-vah-YAY",
                "To work",
                "Je travaille ici.",
                "I work here.",
            ),
            (
                "Le matin",
                "luh mah-TAN",
                "In the morning",
                "J'étudie le matin.",
                "I study in the morning.",
            ),
            (
                "Chaque jour",
                "shahk zhoor",
                "Every day",
                "Je lis chaque jour.",
                "I read every day.",
            ),
        ],
        "Everyday present tense",
        (
            "The endings change when a verb follows je: étudier becomes "
            "j'étudie and travailler becomes je travaille."
        ),
        "Arrange: I study French every day.",
        "J'étudie le français chaque jour",
        "Put the time phrase chaque jour after the activity.",
        ["chaque", "le", "J'étudie", "jour", "français"],
        ["Jetudie le francais chaque jour"],
    ),
    _lesson(
        "fr-beg-8",
        "Time and Plans",
        "🕗",
        "Ask the time and make a simple plan.",
        [
            (
                "Quelle heure est-il ?",
                "kel uhr eh-TEEL",
                "What time is it?",
                "Excusez-moi, quelle heure est-il ?",
                "Excuse me, what time is it?",
            ),
            (
                "Aujourd'hui",
                "oh-zhoor-DWEE",
                "Today",
                "Je travaille aujourd'hui.",
                "I am working today.",
            ),
            (
                "Demain",
                "duh-MAN",
                "Tomorrow",
                "À demain !",
                "See you tomorrow!",
            ),
            (
                "À huit heures",
                "ah weet uhr",
                "At eight o'clock",
                "Le cours commence à huit heures.",
                "The class starts at eight o'clock.",
            ),
            (
                "On se retrouve",
                "ohn suh ruh-TROOV",
                "We will meet up",
                "On se retrouve demain.",
                "We will meet up tomorrow.",
            ),
        ],
        "At a particular time",
        "Use à before a clock time: à huit heures means at eight o'clock.",
        "Arrange: We will meet tomorrow at eight o'clock.",
        "On se retrouve demain à huit heures",
        "Put demain before the clock time.",
        ["à", "On", "heures", "demain", "se", "huit", "retrouve"],
    ),
    _lesson(
        "fr-beg-9",
        "Directions and Travel",
        "🗺️",
        "Ask where a place is and follow directions.",
        [
            (
                "Où est… ?",
                "oo eh",
                "Where is…?",
                "Où est la gare ?",
                "Where is the station?",
            ),
            (
                "À gauche",
                "ah gohsh",
                "On the left",
                "Tournez à gauche.",
                "Turn left.",
            ),
            (
                "À droite",
                "ah drwaht",
                "On the right",
                "La banque est à droite.",
                "The bank is on the right.",
            ),
            (
                "Tout droit",
                "too drwah",
                "Straight ahead",
                "Allez tout droit.",
                "Go straight ahead.",
            ),
            (
                "La gare",
                "lah gahr",
                "The station",
                "La gare est près d'ici.",
                "The station is near here.",
            ),
        ],
        "Describing a location",
        (
            "Use est before a direction: est à gauche means is on the "
            "left, and est à droite means is on the right."
        ),
        "Arrange: The station is on the right.",
        "La gare est à droite",
        "Place the direction after est.",
        ["droite", "gare", "à", "La", "est"],
    ),
]

SPANISH_EXTRA_LESSONS = [
    _lesson(
        "es-beg-4",
        "Family and People",
        "👨‍👩‍👧",
        "Talk about close family members.",
        [
            (
                "La familia",
                "lah fah-MEE-lyah",
                "Family",
                "Esta es mi familia.",
                "This is my family.",
            ),
            (
                "La madre",
                "lah MAH-dreh",
                "Mother",
                "Mi madre se llama Ana.",
                "My mother's name is Ana.",
            ),
            (
                "El padre",
                "el PAH-dreh",
                "Father",
                "Mi padre trabaja aquí.",
                "My father works here.",
            ),
            (
                "El hermano",
                "el ehr-MAH-noh",
                "Brother",
                "Tengo un hermano.",
                "I have a brother.",
            ),
            (
                "La hermana",
                "lah ehr-MAH-nah",
                "Sister",
                "Ella es mi hermana.",
                "She is my sister.",
            ),
        ],
        "The possessive mi",
        (
            "Mi means my and does not change for masculine or feminine: "
            "mi padre and mi madre."
        ),
        "Arrange: She is my sister.",
        "Ella es mi hermana",
        "Use mi directly before the family word.",
        ["hermana", "Ella", "mi", "es"],
    ),
    _lesson(
        "es-beg-5",
        "Numbers and Age",
        "🔢",
        "Count a few things and say your age.",
        [
            ("Uno", "OO-noh", "One", "Tengo un libro.", "I have one book."),
            ("Dos", "dohs", "Two", "Tengo dos amigos.", "I have two friends."),
            ("Diez", "dyehs", "Ten", "Son las diez.", "It is ten o'clock."),
            (
                "Catorce",
                "kah-TOR-seh",
                "Fourteen",
                "Tengo catorce años.",
                "I am fourteen years old.",
            ),
            (
                "¿Cuántos años tienes?",
                "KWAHN-tohs AH-nyohs TYEH-nehs",
                "How old are you? — informal",
                "¿Cuántos años tienes?",
                "How old are you?",
            ),
        ],
        "Talking about age",
        (
            "Spanish uses tener, meaning ‘to have’, for age. Say tengo, "
            "then the number, then años."
        ),
        "Arrange: I am fourteen years old.",
        "Tengo catorce años",
        "Age follows the pattern tengo + number + años.",
        ["años", "catorce", "Tengo"],
        ["Tengo catorce anos"],
    ),
    _lesson(
        "es-beg-6",
        "Food and Ordering",
        "🍽️",
        "Name simple foods and order politely.",
        [
            ("El pan", "el pahn", "Bread", "Como pan.", "I eat bread."),
            (
                "El queso",
                "el KEH-soh",
                "Cheese",
                "Me gusta el queso.",
                "I like cheese.",
            ),
            ("El agua", "el AH-gwah", "Water", "Bebo agua.", "I drink water."),
            (
                "Quisiera…",
                "kee-SYEH-rah",
                "I would like…",
                "Quisiera pan.",
                "I would like bread.",
            ),
            (
                "La cuenta",
                "lah KWEHN-tah",
                "The bill or check",
                "La cuenta, por favor.",
                "The bill, please.",
            ),
        ],
        "Ordering with quisiera",
        "Use quisiera before an item to make a polite order.",
        "Arrange: I would like water, please.",
        "Quisiera agua por favor",
        "Put the item after quisiera and por favor at the end.",
        ["favor", "agua", "Quisiera", "por"],
    ),
    _lesson(
        "es-beg-7",
        "School and Daily Life",
        "🎒",
        "Describe simple parts of your daily routine.",
        [
            (
                "La escuela",
                "lah ehs-KWEH-lah",
                "School",
                "Voy a la escuela.",
                "I go to school.",
            ),
            (
                "Estudiar",
                "ehs-too-DYAHR",
                "To study",
                "Estudio español.",
                "I study Spanish.",
            ),
            (
                "Trabajar",
                "trah-bah-HAHR",
                "To work",
                "Trabajo aquí.",
                "I work here.",
            ),
            (
                "Por la mañana",
                "por lah mah-NYAH-nah",
                "In the morning",
                "Estudio por la mañana.",
                "I study in the morning.",
            ),
            (
                "Todos los días",
                "TOH-dohs lohs DEE-ahs",
                "Every day",
                "Leo todos los días.",
                "I read every day.",
            ),
        ],
        "The subject can be omitted",
        (
            "Spanish verb endings often show who is acting, so yo can be "
            "left out: estudio means I study."
        ),
        "Arrange: I study Spanish every day.",
        "Estudio español todos los días",
        "Put the time phrase todos los días after the activity.",
        ["días", "español", "los", "Estudio", "todos"],
        ["Estudio espanol todos los dias"],
    ),
    _lesson(
        "es-beg-8",
        "Time and Plans",
        "🕗",
        "Ask the time and make a simple plan.",
        [
            (
                "¿Qué hora es?",
                "keh OH-rah ehs",
                "What time is it?",
                "Disculpe, ¿qué hora es?",
                "Excuse me, what time is it?",
            ),
            (
                "Hoy",
                "oy",
                "Today",
                "Trabajo hoy.",
                "I am working today.",
            ),
            (
                "Mañana",
                "mah-NYAH-nah",
                "Tomorrow",
                "Nos vemos mañana.",
                "See you tomorrow.",
            ),
            (
                "A las ocho",
                "ah lahs OH-choh",
                "At eight o'clock",
                "La clase empieza a las ocho.",
                "The class starts at eight o'clock.",
            ),
            (
                "Nos vemos",
                "nohs VEH-mohs",
                "See you or we will meet",
                "Nos vemos pronto.",
                "See you soon.",
            ),
        ],
        "At a particular time",
        (
            "Use a la for one o'clock and a las for other clock times: "
            "a las ocho means at eight."
        ),
        "Arrange: See you tomorrow at eight.",
        "Nos vemos mañana a las ocho",
        "Put mañana before the clock time.",
        ["a", "Nos", "ocho", "mañana", "vemos", "las"],
        ["Nos vemos manana a las ocho"],
    ),
    _lesson(
        "es-beg-9",
        "Directions and Travel",
        "🗺️",
        "Ask where a place is and follow directions.",
        [
            (
                "¿Dónde está…?",
                "DOHN-deh ehs-TAH",
                "Where is…?",
                "¿Dónde está la estación?",
                "Where is the station?",
            ),
            (
                "A la izquierda",
                "ah lah ees-KYEHR-dah",
                "On the left",
                "Gire a la izquierda.",
                "Turn left.",
            ),
            (
                "A la derecha",
                "ah lah deh-REH-chah",
                "On the right",
                "El banco está a la derecha.",
                "The bank is on the right.",
            ),
            (
                "Todo recto",
                "TOH-doh REHK-toh",
                "Straight ahead",
                "Siga todo recto.",
                "Go straight ahead.",
            ),
            (
                "La estación",
                "lah ehs-tah-SYOHN",
                "The station",
                "La estación está cerca.",
                "The station is nearby.",
            ),
        ],
        "Describing a location",
        (
            "Use está before a direction: está a la izquierda means is "
            "on the left."
        ),
        "Arrange: The station is on the right.",
        "La estación está a la derecha",
        "Place the direction after está.",
        ["derecha", "estación", "a", "La", "la", "está"],
        ["La estacion esta a la derecha"],
    ),
]

HINDI_EXTRA_LESSONS = [
    _lesson(
        "hi-beg-4",
        "Family and People",
        "👨‍👩‍👧",
        "Talk about close family members.",
        [
            (
                "परिवार",
                "Parivaar",
                "Family",
                "यह मेरा परिवार है।",
                "This is my family.",
            ),
            (
                "माँ",
                "Maa",
                "Mother",
                "मेरी माँ घर पर हैं।",
                "My mother is at home.",
            ),
            (
                "पिता",
                "Pita",
                "Father",
                "मेरे पिता शिक्षक हैं।",
                "My father is a teacher.",
            ),
            (
                "भाई",
                "Bhaai",
                "Brother",
                "मेरा भाई छात्र है।",
                "My brother is a student.",
            ),
            (
                "बहन",
                "Bahan",
                "Sister",
                "यह मेरी बहन है।",
                "She is my sister.",
            ),
        ],
        "मेरा, मेरी, and मेरे",
        (
            "The word for my changes with the noun: मेरा भाई, मेरी बहन, "
            "and the respectful plural मेरे पिता."
        ),
        "Arrange: She is my sister.",
        "यह मेरी बहन है",
        "Use मेरी with the feminine word बहन.",
        ["बहन", "यह", "है", "मेरी"],
        ["Yah meri bahan hai"],
    ),
    _lesson(
        "hi-beg-5",
        "Numbers and Age",
        "🔢",
        "Count a few things and say your age.",
        [
            ("एक", "Ek", "One", "मेरे पास एक किताब है।", "I have one book."),
            ("दो", "Do", "Two", "मेरे दो दोस्त हैं।", "I have two friends."),
            ("दस", "Das", "Ten", "यह दस रुपये का है।", "This costs ten rupees."),
            (
                "चौदह",
                "Chaudah",
                "Fourteen",
                "मेरी उम्र चौदह साल है।",
                "I am fourteen years old.",
            ),
            (
                "आपकी उम्र क्या है?",
                "Aapki umr kya hai?",
                "How old are you? — polite",
                "आपकी उम्र क्या है?",
                "How old are you?",
            ),
        ],
        "Talking about age",
        (
            "Use मेरी उम्र + number + साल है. This literally says, "
            "‘My age is ... years.’"
        ),
        "Arrange: I am fourteen years old.",
        "मेरी उम्र चौदह साल है",
        "Put the number before साल.",
        ["है", "चौदह", "मेरी", "साल", "उम्र"],
        ["Meri umr chaudah saal hai"],
    ),
    _lesson(
        "hi-beg-6",
        "Food and Ordering",
        "🍛",
        "Name simple foods and ask for something politely.",
        [
            (
                "पानी",
                "Paani",
                "Water",
                "मुझे पानी चाहिए।",
                "I would like water.",
            ),
            (
                "रोटी",
                "Roti",
                "Flatbread",
                "यह रोटी गरम है।",
                "This flatbread is hot.",
            ),
            (
                "चावल",
                "Chaaval",
                "Rice",
                "मुझे चावल पसंद है।",
                "I like rice.",
            ),
            (
                "मुझे … चाहिए",
                "Mujhe … chahiye",
                "I would like or need…",
                "मुझे खाना चाहिए।",
                "I would like food.",
            ),
            (
                "बिल",
                "Bil",
                "The bill or check",
                "बिल दीजिए।",
                "Please give me the bill.",
            ),
        ],
        "Asking with चाहिए",
        (
            "Put the thing you want between मुझे and चाहिए: मुझे पानी "
            "चाहिए means I would like water."
        ),
        "Arrange: I would like water.",
        "मुझे पानी चाहिए",
        "Put the requested item before चाहिए.",
        ["चाहिए", "मुझे", "पानी"],
        ["Mujhe paani chahiye"],
    ),
    _lesson(
        "hi-beg-7",
        "School and Daily Life",
        "🎒",
        "Describe simple parts of your daily routine.",
        [
            (
                "स्कूल",
                "School",
                "School",
                "यह मेरा स्कूल है।",
                "This is my school.",
            ),
            (
                "पढ़ना",
                "Padhna",
                "To study or read",
                "मुझे हिन्दी पढ़ना पसंद है।",
                "I like studying Hindi.",
            ),
            (
                "काम करना",
                "Kaam karna",
                "To work",
                "मुझे यहाँ काम करना है।",
                "I have to work here.",
            ),
            (
                "सुबह",
                "Subah",
                "Morning",
                "मैं सुबह पढ़ता हूँ।",
                "I study in the morning.",
            ),
            (
                "हर दिन",
                "Har din",
                "Every day",
                "हम हर दिन पढ़ते हैं।",
                "We study every day.",
            ),
        ],
        "Verb endings and gender",
        (
            "A boy or man says मैं पढ़ता हूँ; a girl or woman says मैं "
            "पढ़ती हूँ. With हम, use पढ़ते हैं."
        ),
        "Arrange: We study Hindi every day.",
        "हम हर दिन हिन्दी पढ़ते हैं",
        "Put हर दिन before the activity.",
        ["पढ़ते", "हर", "हम", "हिन्दी", "हैं", "दिन"],
        ["Hum har din Hindi padhte hain"],
    ),
    _lesson(
        "hi-beg-8",
        "Time and Plans",
        "🕗",
        "Ask the time and make a simple plan.",
        [
            (
                "कितने बजे हैं?",
                "Kitne baje hain?",
                "What time is it?",
                "अभी कितने बजे हैं?",
                "What time is it now?",
            ),
            ("आज", "Aaj", "Today", "आज सोमवार है।", "Today is Monday."),
            (
                "कल",
                "Kal",
                "Tomorrow or yesterday",
                "हम कल मिलेंगे।",
                "We will meet tomorrow.",
            ),
            (
                "आठ बजे",
                "Aath baje",
                "At eight o'clock",
                "कक्षा आठ बजे शुरू होती है।",
                "Class starts at eight o'clock.",
            ),
            (
                "मिलेंगे",
                "Milenge",
                "Will meet",
                "हम फिर मिलेंगे।",
                "We will meet again.",
            ),
        ],
        "Clock time with बजे",
        "Put बजे after a number to state a clock time: आठ बजे means at eight.",
        "Arrange: We will meet tomorrow at eight.",
        "हम कल आठ बजे मिलेंगे",
        "Put the day before the clock time.",
        ["आठ", "हम", "मिलेंगे", "कल", "बजे"],
        ["Hum kal aath baje milenge"],
    ),
    _lesson(
        "hi-beg-9",
        "Directions and Travel",
        "🗺️",
        "Ask where a place is and follow directions.",
        [
            (
                "कहाँ है?",
                "Kahaan hai?",
                "Where is it?",
                "स्टेशन कहाँ है?",
                "Where is the station?",
            ),
            (
                "बाईं ओर",
                "Baayin or",
                "On the left",
                "बाईं ओर मुड़िए।",
                "Turn left.",
            ),
            (
                "दाईं ओर",
                "Daayin or",
                "On the right",
                "बैंक दाईं ओर है।",
                "The bank is on the right.",
            ),
            (
                "सीधे",
                "Seedhe",
                "Straight ahead",
                "सीधे जाइए।",
                "Go straight ahead.",
            ),
            (
                "स्टेशन",
                "Station",
                "Station",
                "स्टेशन पास में है।",
                "The station is nearby.",
            ),
        ],
        "Describing a location",
        (
            "Put the location before है: दाईं ओर है means is on the right."
        ),
        "Arrange: The station is on the right.",
        "स्टेशन दाईं ओर है",
        "Place दाईं ओर before है.",
        ["है", "ओर", "स्टेशन", "दाईं"],
        ["Station daayin or hai"],
    ),
]

KOREAN_EXTRA_LESSONS = [
    _lesson(
        "ko-beg-4",
        "Family and People",
        "👨‍👩‍👧",
        "Talk about family and a friend.",
        [
            (
                "가족",
                "gajok",
                "Family",
                "제 가족이에요.",
                "This is my family.",
            ),
            (
                "어머니",
                "eomeoni",
                "Mother",
                "제 어머니예요.",
                "This is my mother.",
            ),
            (
                "아버지",
                "abeoji",
                "Father",
                "제 아버지예요.",
                "This is my father.",
            ),
            (
                "부모님",
                "bumonim",
                "Parents — respectful",
                "부모님은 집에 계세요.",
                "My parents are at home.",
            ),
            (
                "친구",
                "chingu",
                "Friend",
                "민수는 제 친구예요.",
                "Minsu is my friend.",
            ),
        ],
        "The polite possessive 제",
        "Put 제 before a noun to say my politely: 제 가족 means my family.",
        "Arrange: Minsu is my friend.",
        "민수는 제 친구예요",
        "Put 제 directly before 친구.",
        ["친구예요", "민수는", "제"],
        ["Minsuneun je chinguyeyo"],
    ),
    _lesson(
        "ko-beg-5",
        "Numbers and Age",
        "🔢",
        "Count a few things and say your age.",
        [
            ("하나", "hana", "One", "사과 하나 주세요.", "Please give me one apple."),
            ("둘", "dul", "Two", "친구가 둘 있어요.", "I have two friends."),
            ("열", "yeol", "Ten", "열 시예요.", "It is ten o'clock."),
            (
                "열네",
                "yeol-ne",
                "Fourteen",
                "저는 열네 살이에요.",
                "I am fourteen years old.",
            ),
            (
                "몇 살이에요?",
                "myeot sar-ieyo?",
                "How old are you? — polite",
                "몇 살이에요?",
                "How old are you?",
            ),
        ],
        "Age with 살이에요",
        (
            "Put a native Korean number before 살이에요 to state an age: "
            "열네 살이에요 means fourteen years old."
        ),
        "Arrange: I am fourteen years old.",
        "저는 열네 살이에요",
        "Put the age between 저는 and 살이에요.",
        ["살이에요", "열네", "저는"],
        ["Jeoneun yeol-ne sar-ieyo", "Jeoneun yeolne salieyo"],
    ),
    _lesson(
        "ko-beg-6",
        "Food and Ordering",
        "🍚",
        "Name simple foods and order politely.",
        [
            ("물", "mul", "Water", "물을 마셔요.", "I drink water."),
            ("밥", "bap", "Rice or a meal", "밥을 먹어요.", "I eat a meal."),
            ("빵", "ppang", "Bread", "빵을 좋아해요.", "I like bread."),
            (
                "주세요",
                "juseyo",
                "Please give me…",
                "물 주세요.",
                "Please give me water.",
            ),
            (
                "계산해 주세요",
                "gyesanhae juseyo",
                "The bill, please",
                "계산해 주세요.",
                "The bill, please.",
            ),
        ],
        "Ordering with 주세요",
        "Put the item before 주세요 to ask for it politely: 물 주세요.",
        "Arrange: Please give me water.",
        "물 주세요",
        "Put the requested item before 주세요.",
        ["주세요", "물"],
        ["Mul juseyo"],
    ),
    _lesson(
        "ko-beg-7",
        "School and Daily Life",
        "🎒",
        "Describe simple parts of your daily routine.",
        [
            (
                "학교",
                "hakgyo",
                "School",
                "학교에 가요.",
                "I go to school.",
            ),
            (
                "공부하다",
                "gongbuhada",
                "To study",
                "한국어를 공부해요.",
                "I study Korean.",
            ),
            (
                "일하다",
                "ilhada",
                "To work",
                "여기에서 일해요.",
                "I work here.",
            ),
            (
                "아침",
                "achim",
                "Morning",
                "아침에 공부해요.",
                "I study in the morning.",
            ),
            (
                "매일",
                "maeil",
                "Every day",
                "저는 매일 읽어요.",
                "I read every day.",
            ),
        ],
        "A basic Korean sentence",
        (
            "Use 저는 for I as the topic. Add 를 after the object, then "
            "place the action at the end."
        ),
        "Arrange: I study Korean every day.",
        "저는 매일 한국어를 공부해요",
        "Korean places the action 공부해요 at the end.",
        ["공부해요", "저는", "한국어를", "매일"],
        ["Jeoneun maeil hangugeoreul gongbuhaeyo"],
    ),
    _lesson(
        "ko-beg-8",
        "Time and Plans",
        "🕗",
        "Ask the time and make a simple plan.",
        [
            (
                "몇 시예요?",
                "myeot siyeyo?",
                "What time is it?",
                "지금 몇 시예요?",
                "What time is it now?",
            ),
            ("오늘", "oneul", "Today", "오늘 공부해요.", "I study today."),
            (
                "내일",
                "naeil",
                "Tomorrow",
                "내일 만나요.",
                "See you tomorrow.",
            ),
            (
                "여덟 시",
                "yeodeol si",
                "Eight o'clock",
                "수업은 여덟 시에 시작해요.",
                "Class starts at eight o'clock.",
            ),
            (
                "만나요",
                "mannayo",
                "Meet or see you",
                "학교에서 만나요.",
                "Let's meet at school.",
            ),
        ],
        "Time with 에",
        "Add 에 after a clock time to mean at that time: 여덟 시에.",
        "Arrange: Let's meet tomorrow at eight.",
        "내일 여덟 시에 만나요",
        "Put 에 after the clock time and the action last.",
        ["만나요", "시에", "내일", "여덟"],
        ["Naeil yeodeol sie mannayo"],
    ),
    _lesson(
        "ko-beg-9",
        "Directions and Travel",
        "🗺️",
        "Ask where a place is and follow directions.",
        [
            (
                "어디예요?",
                "eodiyeyo?",
                "Where is it?",
                "역이 어디예요?",
                "Where is the station?",
            ),
            (
                "왼쪽",
                "oenjjok",
                "Left",
                "왼쪽으로 가세요.",
                "Go to the left.",
            ),
            (
                "오른쪽",
                "oreunjjok",
                "Right",
                "은행은 오른쪽에 있어요.",
                "The bank is on the right.",
            ),
            (
                "곧장",
                "gotjang",
                "Straight ahead",
                "곧장 가세요.",
                "Go straight ahead.",
            ),
            (
                "역",
                "yeok",
                "Station",
                "역은 가까워요.",
                "The station is nearby.",
            ),
        ],
        "Location with 에 있어요",
        (
            "Put 에 있어요 after a place or direction to say where "
            "something is."
        ),
        "Arrange: The station is on the right.",
        "역은 오른쪽에 있어요",
        "Place the direction before 에 있어요.",
        ["있어요", "역은", "오른쪽에"],
        ["Yeogeun oreunjjoge isseoyo"],
    ),
]

JAPANESE_EXTRA_LESSONS = [
    _lesson(
        "ja-beg-4",
        "Family and People",
        "👨‍👩‍👧",
        "Talk about your family and a friend.",
        [
            (
                "家族",
                "kazoku",
                "Family",
                "これは私の家族です。",
                "This is my family.",
            ),
            (
                "母",
                "haha",
                "My mother",
                "母は先生です。",
                "My mother is a teacher.",
            ),
            (
                "父",
                "chichi",
                "My father",
                "父は会社員です。",
                "My father is an office worker.",
            ),
            (
                "兄",
                "ani",
                "My older brother",
                "兄は学生です。",
                "My older brother is a student.",
            ),
            (
                "友だち",
                "tomodachi",
                "Friend",
                "ケンさんは私の友だちです。",
                "Ken is my friend.",
            ),
        ],
        "The possessive particle の",
        "Put の after 私 to say my: 私の家族 means my family.",
        "Arrange: This is my family.",
        "これは私の家族です",
        "Use の between 私 and 家族.",
        ["家族です", "これは", "私の"],
        ["Kore wa watashi no kazoku desu"],
    ),
    _lesson(
        "ja-beg-5",
        "Numbers and Age",
        "🔢",
        "Count a few things and say your age.",
        [
            ("一", "ichi", "One", "りんごが一つあります。", "There is one apple."),
            ("二", "ni", "Two", "本が二冊あります。", "There are two books."),
            ("十", "juu", "Ten", "十時です。", "It is ten o'clock."),
            (
                "十四歳",
                "juuyon-sai",
                "Fourteen years old",
                "私は十四歳です。",
                "I am fourteen years old.",
            ),
            (
                "何歳ですか？",
                "nan-sai desu ka?",
                "How old are you? — polite",
                "何歳ですか？",
                "How old are you?",
            ),
        ],
        "Age with 歳です",
        "Put the age before 歳です. 十四歳です means fourteen years old.",
        "Arrange: I am fourteen years old.",
        "私は十四歳です",
        "Put the age between 私は and です.",
        ["十四歳です", "私は"],
        ["Watashi wa juuyon-sai desu"],
    ),
    _lesson(
        "ja-beg-6",
        "Food and Ordering",
        "🍱",
        "Name simple foods and order politely.",
        [
            ("水", "mizu", "Water", "水を飲みます。", "I drink water."),
            ("ご飯", "gohan", "Rice or a meal", "ご飯を食べます。", "I eat a meal."),
            ("パン", "pan", "Bread", "パンが好きです。", "I like bread."),
            (
                "ください",
                "kudasai",
                "Please give me…",
                "水をください。",
                "Please give me water.",
            ),
            (
                "お会計",
                "okaikei",
                "The bill or check",
                "お会計をお願いします。",
                "The bill, please.",
            ),
        ],
        "Ordering with をください",
        "Put the requested item before をください: 水をください.",
        "Arrange: Please give me water.",
        "水をください",
        "Put を between the item and ください.",
        ["ください", "水", "を"],
        ["Mizu o kudasai"],
    ),
    _lesson(
        "ja-beg-7",
        "School and Daily Life",
        "🎒",
        "Describe simple parts of your daily routine.",
        [
            (
                "学校",
                "gakkou",
                "School",
                "学校へ行きます。",
                "I go to school.",
            ),
            (
                "勉強します",
                "benkyou shimasu",
                "Study",
                "日本語を勉強します。",
                "I study Japanese.",
            ),
            (
                "働きます",
                "hatarakimasu",
                "Work",
                "ここで働きます。",
                "I work here.",
            ),
            (
                "朝",
                "asa",
                "Morning",
                "朝に勉強します。",
                "I study in the morning.",
            ),
            (
                "毎日",
                "mainichi",
                "Every day",
                "私は毎日読みます。",
                "I read every day.",
            ),
        ],
        "The object particle を",
        "Put を after the object and place the action at the end.",
        "Arrange: I study Japanese every day.",
        "私は毎日日本語を勉強します",
        "Japanese places the action 勉強します at the end.",
        ["勉強します", "私は", "日本語を", "毎日"],
        ["Watashi wa mainichi nihongo o benkyou shimasu"],
    ),
    _lesson(
        "ja-beg-8",
        "Time and Plans",
        "🕗",
        "Ask the time and make a simple plan.",
        [
            (
                "何時ですか？",
                "nanji desu ka?",
                "What time is it?",
                "今、何時ですか？",
                "What time is it now?",
            ),
            ("今日", "kyou", "Today", "今日は勉強します。", "I will study today."),
            (
                "明日",
                "ashita",
                "Tomorrow",
                "また明日。",
                "See you tomorrow.",
            ),
            (
                "八時",
                "hachiji",
                "Eight o'clock",
                "授業は八時に始まります。",
                "Class starts at eight o'clock.",
            ),
            (
                "会います",
                "aimasu",
                "Meet",
                "学校で会います。",
                "We will meet at school.",
            ),
        ],
        "Time with に",
        "Put に after a clock time to mean at that time: 八時に.",
        "Arrange: We will meet tomorrow at eight.",
        "明日八時に会います",
        "Put に after the clock time and the action last.",
        ["会います", "明日", "八時に"],
        ["Ashita hachiji ni aimasu"],
    ),
    _lesson(
        "ja-beg-9",
        "Directions and Travel",
        "🗺️",
        "Ask where a place is and follow directions.",
        [
            (
                "どこですか？",
                "doko desu ka?",
                "Where is it?",
                "駅はどこですか？",
                "Where is the station?",
            ),
            (
                "左",
                "hidari",
                "Left",
                "左へ曲がってください。",
                "Please turn left.",
            ),
            (
                "右",
                "migi",
                "Right",
                "銀行は右にあります。",
                "The bank is on the right.",
            ),
            (
                "まっすぐ",
                "massugu",
                "Straight ahead",
                "まっすぐ行ってください。",
                "Please go straight ahead.",
            ),
            (
                "駅",
                "eki",
                "Station",
                "駅は近いです。",
                "The station is nearby.",
            ),
        ],
        "Location with にあります",
        "Use にあります after a direction to say where something is.",
        "Arrange: The station is on the right.",
        "駅は右にあります",
        "Place the direction before にあります.",
        ["右に", "駅は", "あります"],
        ["Eki wa migi ni arimasu"],
    ),
]


EXTRA_LESSONS = {
    "French": FRENCH_EXTRA_LESSONS,
    "Spanish": SPANISH_EXTRA_LESSONS,
    "Hindi": HINDI_EXTRA_LESSONS,
    "Korean": KOREAN_EXTRA_LESSONS,
    "Japanese": JAPANESE_EXTRA_LESSONS,
}


def get_extra_lessons(language):
    """Return a safe copy of a language's additional lessons."""
    return deepcopy(EXTRA_LESSONS.get(language, []))

